  Activating project at `/data/gpfs/projects/punim0638/stephenz/locaTE-paper/data/simulated/Synthetic_1000/dyn-LI/dyn-LI-1000-2/pidc_env`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `/data/gpfs/projects/punim0638/stephenz/locaTE-paper/data/simulated/Synthetic_1000/dyn-LI/dyn-LI-1000-2/pidc_env/Project.toml`
  No Changes to `/data/gpfs/projects/punim0638/stephenz/locaTE-paper/data/simulated/Synthetic_1000/dyn-LI/dyn-LI-1000-2/pidc_env/Manifest.toml`
Getting nodes...
Inferring network...
cat: write error: Broken pipe
2023-10-04 23:39:11.493122
2023-10-04 23:39:11.881725
2023-10-04 23:39:12.301110

real	0m1.676s
user	0m0.006s
sys	0m0.012s
cat: write error: Broken pipe
2023-10-04 23:39:23.364494
2023-10-04 23:39:23.654528
2023-10-04 23:39:24.049775

real	0m1.565s
user	0m0.009s
sys	0m0.008s
cat: write error: Broken pipe
2023-10-04 23:39:35.085501
2023-10-04 23:39:35.335136
2023-10-04 23:39:35.711595

real	0m1.453s
user	0m0.007s
sys	0m0.010s
cat: write error: Broken pipe
2023-10-04 23:39:46.795915
2023-10-04 23:39:47.077741
2023-10-04 23:39:47.461536

real	0m1.559s
user	0m0.009s
sys	0m0.008s
cat: write error: Broken pipe
2023-10-04 23:39:58.661595
2023-10-04 23:39:59.238114
2023-10-04 23:39:59.698556

real	0m2.046s
user	0m0.009s
sys	0m0.007s
cat: write error: Broken pipe
2023-10-04 23:40:10.750717
2023-10-04 23:40:11.425238
2023-10-04 23:40:12.134519

real	0m2.239s
user	0m0.008s
sys	0m0.009s
cat: write error: Broken pipe
2023-10-04 23:40:23.117534
2023-10-04 23:40:23.755074
2023-10-04 23:40:24.562388

real	0m2.238s
user	0m0.007s
sys	0m0.010s
cat: write error: Broken pipe
2023-10-04 23:40:35.536279
2023-10-04 23:40:35.720071
2023-10-04 23:40:35.910414

real	0m1.156s
user	0m0.008s
sys	0m0.009s
mkdir: cannot create directory ‘SCODE_D_2’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
mkdir: cannot create directory ‘SCODE_D_4’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
mkdir: cannot create directory ‘SCODE_D_6’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
mkdir: cannot create directory ‘SCODE_D_8’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
sh: line 1: matlab: command not found
sh: line 1: matlab: command not found
/data/gpfs/projects/punim0638/stephenz/envs/py39/lib/python3.9/site-packages/Scribe-0.0.0-py3.9.egg/Scribe/causal_network.py:18: UserWarning:  WARNING: No expression data argument given. if you intend to load the data from a file, call the method 'read_expression_file'.
  if expression==None: warnings.warn(" WARNING: No expression data argument given. if you intend to load the data from a file, call the method 'read_expression_file'.")
/data/gpfs/projects/punim0638/stephenz/envs/py39/lib/python3.9/site-packages/Scribe-0.0.0-py3.9.egg/Scribe/causal_network.py:298: FutureWarning: Could not cast to int64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  max_rdi_delay = pd.DataFrame({node_id: [np.nan for i in self.node_ids] for node_id in self.node_ids}, index=self.node_ids,
Tree method: RF
K: sqrt
Number of trees: 1000


running single threaded jobs
Gene 1/7...
Gene 2/7...
Gene 3/7...
Gene 4/7...
Gene 5/7...
Gene 6/7...
Gene 7/7...
Elapsed time: 13.73 seconds
Create causal_model successfully
