  Activating project at `/data/gpfs/projects/punim0638/stephenz/locaTE-paper/data/simulated/Synthetic_1000/dyn-SW/dyn-SW-1000-6/pidc_env`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `/data/gpfs/projects/punim0638/stephenz/locaTE-paper/data/simulated/Synthetic_1000/dyn-SW/dyn-SW-1000-6/pidc_env/Project.toml`
  No Changes to `/data/gpfs/projects/punim0638/stephenz/locaTE-paper/data/simulated/Synthetic_1000/dyn-SW/dyn-SW-1000-6/pidc_env/Manifest.toml`
Getting nodes...
Inferring network...
cat: write error: Broken pipe
2023-10-04 23:45:14.419720
2023-10-04 23:45:14.781334
2023-10-04 23:45:15.141895

real	0m1.608s
user	0m0.008s
sys	0m0.011s
cat: write error: Broken pipe
2023-10-04 23:45:26.178452
2023-10-04 23:45:26.512426
2023-10-04 23:45:26.832221

real	0m1.497s
user	0m0.007s
sys	0m0.010s
cat: write error: Broken pipe
2023-10-04 23:45:37.899477
2023-10-04 23:45:38.210015
2023-10-04 23:45:38.499437

real	0m1.484s
user	0m0.007s
sys	0m0.011s
cat: write error: Broken pipe
2023-10-04 23:45:49.534119
2023-10-04 23:45:49.849239
2023-10-04 23:45:50.145703

real	0m1.446s
user	0m0.008s
sys	0m0.009s
cat: write error: Broken pipe
2023-10-04 23:46:01.193693
2023-10-04 23:46:01.575624
2023-10-04 23:46:01.903477

real	0m1.568s
user	0m0.008s
sys	0m0.009s
cat: write error: Broken pipe
2023-10-04 23:46:12.996583
2023-10-04 23:46:13.748770
2023-10-04 23:46:14.425056

real	0m2.328s
user	0m0.007s
sys	0m0.011s
cat: write error: Broken pipe
2023-10-04 23:46:25.419702
2023-10-04 23:46:26.320782
2023-10-04 23:46:27.687580

real	0m3.078s
user	0m0.006s
sys	0m0.011s
cat: write error: Broken pipe
2023-10-04 23:46:38.696323
2023-10-04 23:46:38.868637
2023-10-04 23:46:39.032710

real	0m1.153s
user	0m0.007s
sys	0m0.010s
mkdir: cannot create directory ‘SCODE_D_2’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
mkdir: cannot create directory ‘SCODE_D_4’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
mkdir: cannot create directory ‘SCODE_D_6’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
mkdir: cannot create directory ‘SCODE_D_8’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
sh: line 1: matlab: command not found
sh: line 1: matlab: command not found
/data/gpfs/projects/punim0638/stephenz/envs/py39/lib/python3.9/site-packages/Scribe-0.0.0-py3.9.egg/Scribe/causal_network.py:18: UserWarning:  WARNING: No expression data argument given. if you intend to load the data from a file, call the method 'read_expression_file'.
  if expression==None: warnings.warn(" WARNING: No expression data argument given. if you intend to load the data from a file, call the method 'read_expression_file'.")
/data/gpfs/projects/punim0638/stephenz/envs/py39/lib/python3.9/site-packages/Scribe-0.0.0-py3.9.egg/Scribe/causal_network.py:298: FutureWarning: Could not cast to int64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  max_rdi_delay = pd.DataFrame({node_id: [np.nan for i in self.node_ids] for node_id in self.node_ids}, index=self.node_ids,
Tree method: RF
K: sqrt
Number of trees: 1000


running single threaded jobs
Gene 1/7...
Gene 2/7...
Gene 3/7...
Gene 4/7...
Gene 5/7...
Gene 6/7...
Gene 7/7...
Elapsed time: 13.00 seconds
Create causal_model successfully
